applications/noticia/urls.py
app_name = "noticia_app"

from django.urls import path
from .views import NoticiasInfobaeShowAPIView,NoticiasInfobaeAPIView, NoticiasTnAPIView, NoticiasTelefeShowAPIView,NoticiasTelefeAPIView, NoticiasTnShowAPIView, NoticiasclarinAPIView
from . import views 
urlpatterns = [
        path('',
         views.List_all_noticiasListView.as_view(),
         name='inicio'
         ),
        path('instagram-views',
         views.InstagramViews.as_view(),
         name='instagram'
         ),
        path('buscador-imagenes',
         views.Google_imagenes_Views.as_view(),
         name='buscador_imagenes'
         ),
    path('noticia-categoria/', views.ListNoticiaCategoria.as_view(), name='noticia_categoria'),
    path('noticia-medio/', views.ListNoticiaMedios.as_view(), name='noticia_medio'),
    path('api/noticias/infobae/show/', NoticiasInfobaeShowAPIView.as_view(), name='noticias-infobae-show'),
    path('api/noticias/infobae/', NoticiasInfobaeAPIView.as_view(), name='noticias-infobae'),
    path('api/noticias/tn/', NoticiasTnAPIView.as_view(), name='noticias-tn'),
    path('api/noticias/tn/show/', NoticiasTnShowAPIView.as_view(), name='noticias-tn-show'),
    path('api/noticias/telefe/show/', NoticiasTelefeShowAPIView.as_view(), name='noticias-telefe'),
    path('api/noticias/telefe/', NoticiasTelefeAPIView.as_view(), name='noticias-telefe'),
    path('api/noticias/clarin/', NoticiasclarinAPIView.as_view(), name='noticias-clarin'),
    path('detail-noticia/<pk>/', views.NoticiasDetailView.as_view(), name='noticia_detail'),
    path('', views.NoticiasDetailView.as_view(), name='noticia_detail_dentro'),
]

noticias/noticias/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

noticias/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.noticia.urls')),
]

applications/noticia/models.py
from django.db import models
from applications.medio.models import Medio
from .managers import NoticiaManager



class Categoria(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre.upper()

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()  # o .lower(), como prefieras
        super().save(*args, **kwargs)


class Noticia(models.Model):
    titulo = models.CharField(max_length=500)
    descripcion = models.TextField()
    contenido = models.TextField(default="Texto por defecto")
    fecha = models.DateTimeField(("Fecha"), auto_now=False, auto_now_add=False)
    portada = models.URLField(max_length=500, blank=True)
    categoria = models.ForeignKey(Categoria, 
                                on_delete=models.CASCADE,
                                related_name= 'categoria_noticia'
                                )
    medio = models.ForeignKey(Medio, on_delete=models.CASCADE)
    visitas = models.PositiveBigIntegerField(default=0)
    url = models.URLField(max_length=500, blank=True)
    objects = NoticiaManager()

    def __str__(self):
        return self.titulo
    

class NoticiaImagen(models.Model):
    noticia = models.ForeignKey(
        Noticia,
        on_delete=models.CASCADE,
        related_name='imagenes'
    )
    url = models.URLField(max_length=500)

    def __str__(self):
        return f"Imagen de: {self.noticia.titulo}"

applications/noticia/forms.py
# applications/noticia/forms.py

from django import forms
from .models import Categoria

class CategoriaForm(forms.Form):
    categorias = forms.ModelMultipleChoiceField(
        queryset=Categoria.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

applications/noticia/views.py
from django.urls import reverse_lazy
from django.db.models import Case, When, IntegerField
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.views.generic import TemplateView, ListView, DetailView
from .services.infobae.infobae_scraper_show import scrape_infobae_show
from .services.infobae.infobae_scraper_general import scrape_infobae_general
from .services.tn.tn_scraper_general import scrape_tn_general
from .services.tn.tn_scraper_show import scrape_tn_show
from .services.telefe.telefe_scraper_show import scrape_telefe_show
from .services.telefe.telefe_scraper_general import scrape_telefe_general
from .services.clarin.clarin_scraper_general import scrape_clarin_general
from .models import Noticia
from .forms import CategoriaForm
from applications.medio.forms import MedioForm


# Vista que muestra los detalles de un empleado específico
class NoticiasDetailView(DetailView):
    model = Noticia  # Se usa el modelo Empleado
    template_name = 'noticia/noticia_detail.html'  # Plantilla a renderizar
    # No devuelve una lista, sino un objeto individual, no se necesita un bucle en el template

# Vista que muestra una plantilla estática de presentación
class InstagramViews(TemplateView):
    template_name = 'instagram/instagram.html'

# Vista que muestra una plantilla estática de presentación
class Google_imagenes_Views(TemplateView):
    template_name = 'google/buscador_imagenes.html'
    
class NoticiasInfobaeShowAPIView(APIView):
    def get(self, request):
        data = scrape_infobae_show()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)
    
class NoticiasInfobaeAPIView(APIView):
    def get(self, request):
        data = scrape_infobae_general()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)
    
class NoticiasTnAPIView(APIView):
    def get(self, request):
        data = scrape_tn_general()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)
    
class NoticiasclarinAPIView(APIView):
    def get(self, request):
        data = scrape_clarin_general()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)
    

class NoticiasTnShowAPIView(APIView):
    def get(self, request):
        data = scrape_tn_show()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)
        
    
class NoticiasTelefeShowAPIView(APIView):
    def get(self, request):
        data = scrape_telefe_show()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)


class NoticiasTelefeAPIView(APIView):
    def get(self, request):
        data = scrape_telefe_general()
            # Redirección tras la creación exitosa
        if isinstance(data, tuple):  # Error handling (data, status_code)
            return Response(data[0], status=data[1])

        return Response(data, status=status.HTTP_200_OK)


class List_all_noticiasListView(ListView):
    model = Noticia
    context_object_name = 'noticias'
    template_name = 'noticia/noticia_list.html'
    paginate_by = 300

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '').strip()
        f1 = self.request.GET.get('fecha1', '').strip()
        f2 = self.request.GET.get('fecha2', '').strip()

        # Usamos el manager según los filtros
        if f1 and f2:
            queryset = Noticia.objects.buscar_noticia(f1, f2)
        elif palabra_clave:
            queryset = Noticia.objects.buscar_noticia_titulo(palabra_clave)
        else:
            queryset = Noticia.objects.buscar_noticia()

        # Anotamos la prioridad
        queryset = queryset.annotate(
            prioridad=Case(
                When(categoria__nombre__iexact='ESPECTACULOS', then=0),
                When(categoria__nombre__iexact='DEPORTES', then=1),
                When(categoria__nombre__iexact='POLITICA', then=2),
                default=3,
                output_field=IntegerField(),
            )
        )

        # Ordenar por prioridad y fecha (ya ordenado por fecha ascendente/descendente según el manager)
        return queryset.order_by('prioridad', 'fecha' if f1 and f2 else '-fecha')

            
                       

class ListNoticiaCategoria(ListView):
    model = Noticia
    context_object_name = 'noticias'
    template_name = 'noticia/lista_noticia_categoria.html'
    #paginate_by = 30  # Se establece la paginación en 5 noticias por página


    def get_queryset(self):
        categorias = self.request.GET.getlist('categorias')
        if categorias:
            return Noticia.objects.filter(categoria__id__in=categorias).order_by('-fecha')
        return Noticia.objects.all().order_by('-fecha')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CategoriaForm(self.request.GET)
        return context

class ListNoticiaMedios(ListView):
    model = Noticia
    context_object_name = 'noticias'
    template_name = 'noticia/lista_noticia_medio.html'
    #paginate_by = 30

    def get_queryset(self):
        medio_id = self.request.GET.get('medio')
        queryset = Noticia.objects.all()
        if medio_id:
            queryset = queryset.filter(medio__id=medio_id)
        return queryset.order_by('-fecha')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = MedioForm(self.request.GET)
        return context

templates/noticia/lista_noticia_categoria.html
{% extends "base.html" %}
{% load static %}
{% block title %} Noticias {% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<div class="div_foto_perfil">
  <img src="{% static 'img/LOGODESENCHUFADAS2-TRANSPARENTE.svg' %}" alt="Logo de Desenchufadas" />
</div>

<h1 class="titulo-principal">
  PLATAFORMA DE MEDIOS DIGITALES
</h1>

<section class="contenedor-filtro">
  <h3 class="subtitulo-filtro">
    BUSCAR NOTICIAS POR CATEGORIA
  </h3>

  <form method="get" class="filtro-form">
    <div class="div_checkbox">
    {% for checkbox in form.categorias %}
      <label class="categoria-checkbox">
        {{ checkbox.tag }}
        {{ checkbox.choice_label }}
      </label>
    {% endfor %}
</div>
    <div class="boton-filtrar">
      <button type="submit">
        FILTRAR POR CATEGORIA
      </button>
    </div>
  </form>
</section>

<style>
  .categoria-checkbox {
    background: white;
    border: 2px solid transparent;
    border-radius: 10px;
    padding: 8px 8px;
    font-weight: 600;
    color: #333;
    font-family: 'Montserrat', sans-serif;
    display: flex;
    align-items: center;
    gap: 10px;
    cursor: pointer;
    transition: all 0.2s ease-in-out;
  }

  .categoria-checkbox:hover {
    background: #f3f3f3;
  }

  .categoria-checkbox input[type="checkbox"] {
    display: none;
  }

  .categoria-checkbox input[type="checkbox"]:checked + span,
  .categoria-checkbox input[type="checkbox"]:checked ~ * {
    font-weight: bold;
    color: #ce00a3;
  }

  .categoria-checkbox input[type="checkbox"]:checked + span::before,
  .categoria-checkbox input[type="checkbox"]:checked {
    outline: 2px solid #ce00a3;
    background-color: #ffe6f5;
    border-radius: 8px;
  }

  .categoria-checkbox:has(input[type="checkbox"]:checked) {
    border-color: #ce00a3;
    background-color:rgb(250, 178, 221);
  }
</style>

{% endblock content %}

templates/noticia/lista_noticia_medio.html
{% extends "base.html" %}
{% load static %}
{% block title %} Noticias {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="div-foto-perfil">
  <img
    src="{% static 'img/LOGODESENCHUFADAS2-TRANSPARENTE.svg' %}"
    alt="Logo de Desenchufadas"
  />
</div>

<h1 class="titulo-principal">
  PLATAFORMA DE MEDIOS DIGITALES
</h1>

<section class="seccion-principal">
  <h3>BUSCAR NOTICIAS POR MEDIOS</h3>
  <form method="get" class="formulario-busqueda">
    {% for field in form %}
    <div class="campo-formulario">
      <label class="label-campo">{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}
    <div class="boton-container">
      <button type="submit" class="boton-submit">
        FILTRAR POR MEDIO
      </button>
    </div>
  </form>
</section>

{% endblock content %}

templates/noticia/noticia_detail.html
{% extends "base.html" %}
{% load static %}

<html>
  <head>
    {% block meta_og %}
    <meta property="og:title" content="{{ object.titulo }}" />
    <meta
      property="og:description"
      content="{{ object.descripcion|truncatechars:120 }}"
    />
    <meta property="og:image" content="{{ object.portada }}" />
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    {% endblock %}

    <title>{% block title %} NOTICIA COMPARTIDA {% endblock title %}</title>
    <style>
      .card {
        max-width: 350px;
        margin: auto;
      }
      .card img {
        width: 100%;
        max-height: 200px;
        object-fit: cover;
      }
    </style>
  </head>

  <body>
    {% block content %} {% include 'includes/header.html' %}

    <div class="noticias-container">
      <div class="noticia-card">
        <p class="noticia-fecha">
          <strong>Fecha de publicación:</strong> {{ object.fecha }}:00 hs
        </p>
        <div class="compartir-redes" style="margin: 32px 0px 32px 0px">
          <p class="titulo_compartir_noticia">COMPARTIR NOTICIA</p>
          <!-- WhatsApp -->
          <a
            href="https://wa.me/?text={{ p.titulo|urlencode }}%0A{{ request.build_absolute_uri|slice:':-1' }}{% url 'noticia_app:noticia_detail_dentro'%}"
            target="_blank"
            title="Compartir por WhatsApp"
          >
            <img
              src="{% static 'img/icons/whatsapp.png' %}"
              alt="WhatsApp"
              width="50"
            />
          </a>
          <!-- Facebook -->
          <a
            href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri|slice:':-1' }}{% url 'noticia_app:noticia_detail_dentro'%}"
            target="_blank"
            title="Compartir en Facebook"
          >
            <img
              src="{% static 'img/icons/facebook.png' %}"
              alt="Facebook"
              width="50"
            />
          </a>
        </div>
        <p><strong>Medio:</strong> {{ object.medio }}</p>
        <p><strong>Categoría:</strong> {{ object.categoria }}</p>

        <h4 class="noticia-titulo">{{ object.titulo }}</h4>

        <img src="{{ object.portada }}" alt="Portada" class="noticia-portada" />
        <p><strong>Descripción:</strong> {{ object.descripcion }}</p>
        <p class="p_content_acordeon">
          <strong>Contenido:</strong> {{ object.contenido|safe }}
        </p>

        <div class="noticia-imagenes-adicionales">
          <h5 class="noticia-titulo">Imágenes adicionales</h5>
          {% if object.imagenes.all %}
          <div style="display: flex; gap: 10px; flex-wrap: wrap">
            {% for img in object.imagenes.all %}
            <img
              src="{{ img.url }}"
              alt="Imagen relacionada {{ forloop.counter }}"
              style="
                margin: auto;
                object-fit: cover;
                border-radius: 5px;
              "
            />
            {% endfor %}
          </div>
          {% else %}
          <p>No hay imágenes adicionales.</p>
          {% endif %}
        </div>
            <p style="margin-top: 10px">
            <a href="{{ object.url }}" target="_blank">Leer más</a>
          </p>
          <p><strong>Visitas:</strong> {{ object.visitas }}</p>
      </div>
    </div>

    {% endblock content %}
  </body>
</html>

templates/noticia/noticia_list.html
{% extends "base.html" %}
{% load static %}
{% block title %} GonDigital {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="div-foto-perfil">
  <img
    src="{% static 'img/LOGODESENCHUFADAS2-TRANSPARENTE.svg' %}"
    alt="Logo de Desenchufadas"
    class="logo"
  />
</div>

<h1 class="titulo-principal">
  PLATAFORMA DE MEDIOS DIGITALES
</h1>

<section class="busqueda-noticias">
  <h3 class="titulo-buscar">BUSCAR NOTICIAS</h3>
  <form method="get" class="form-busqueda">
    <p class="rango_fechas" style="color:white">Buscar por título</p>
    <input type="text" id="kword" name="kword" placeholder="Ingrese título..." value="{{ request.GET.kword }}" class="input-busqueda" style="background-color: unset; color:white;" />
    
    <p class="rango_fechas" style="color:white">Fecha de inicio</p>
    <input type="date" name="fecha1" id="fecha1" value="{{ request.GET.fecha1 }}" class="input-busqueda" style="background-color: unset; color:white;" />
    
    <p class="rango_fechas" style="color:white">Fecha de final</p>
    <input type="date" name="fecha2" id="fecha2" value="{{ request.GET.fecha2 }}" class="input-busqueda" style="background-color: unset; color:white;" />
    
    <button type="submit" class="btn-consultar">CONSULTAR</button>
  </form>
</section>


<div class="contenedor-noticias">
  <div id="mensaje">
    <div id="spinner" class="div-cargando">
      <i class="fas fa-spinner fa-spin icon-spinner"></i>
      <h5 class="texto-cargando">Cargando noticias...</h5>
    </div>
  </div>
</div>

{% endblock content %}