applications/noticia/urls.py
app_name = "noticia_app"

from django.urls import path
from .views import NoticiasInfobaeShowAPIView,NoticiasInfobaeAPIView, NoticiasTnAPIView, NoticiasTelefeShowAPIView,NoticiasTelefeAPIView, NoticiasTnShowAPIView, NoticiasclarinAPIView
from . import views 
urlpatterns = [
        path('',
         views.List_all_noticiasListView.as_view(),
         name='inicio'
         ),
        path('instagram-views',
         views.InstagramViews.as_view(),
         name='instagram'
         ),
        path('buscador-imagenes',
         views.Google_imagenes_Views.as_view(),
         name='buscador_imagenes'
         ),
    path('noticia-categoria/', views.ListNoticiaCategoria.as_view(), name='noticia_categoria'),
    path('noticia-medio/', views.ListNoticiaMedios.as_view(), name='noticia_medio'),
    path('api/noticias/infobae/show/', NoticiasInfobaeShowAPIView.as_view(), name='noticias-infobae-show'),
    path('api/noticias/infobae/', NoticiasInfobaeAPIView.as_view(), name='noticias-infobae'),
    path('api/noticias/tn/', NoticiasTnAPIView.as_view(), name='noticias-tn'),
    path('api/noticias/tn/show/', NoticiasTnShowAPIView.as_view(), name='noticias-tn-show'),
    path('api/noticias/telefe/show/', NoticiasTelefeShowAPIView.as_view(), name='noticias-telefe'),
    path('api/noticias/telefe/', NoticiasTelefeAPIView.as_view(), name='noticias-telefe'),
    path('api/noticias/clarin/', NoticiasclarinAPIView.as_view(), name='noticias-clarin'),
    path('detail-noticia/<pk>/', views.NoticiasDetailView.as_view(), name='noticia_detail'),
    path('', views.NoticiasDetailView.as_view(), name='noticia_detail_dentro'),
]

noticias/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.noticia.urls')),
]

templates/includes/header.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Menú Responsive Foundation</title>
  <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/header.css' %}">
</head>
<body>

  <!-- Menú responsive: hamburguesa en móvil, horizontal en desktop -->
  <div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="medium">
    <button class="menu-icon" type="button" data-toggle></button>
    <div class="title-bar-title"></div>
  </div>

  <div class="top-bar" id="main-menu">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li><a href="{% url 'noticia_app:inicio' %}" class="menu-link">INICIO</a></li>
        <li><a href="{% url 'noticia_app:noticia_categoria' %}" class="menu-link">CATEGORIA</a></li>
        <li><a href="{% url 'noticia_app:noticia_medio' %}" class="menu-link">MEDIOS</a></li>
        <li><a href="{% url 'noticia_app:instagram' %}" class="menu-link">INSTAGRAM</a></li>
        <li><a href="{% url 'noticia_app:buscador_imagenes' %}" class="menu-link">BUSCADOR DE IMÁGENES</a></li>
      </ul>
    </div>
  </div>
</body>
</html>